version: "3.3"
services:
  test-db:
    image: mysql
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - "./tests/_data/:/docker-entrypoint-initdb.d"
