version: "3.3"
services:
  app:
    build: .
    ports:
      - 5001:5000
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
  db:
    image: mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - /data/mysql:/var/lib/mysql
